sudo: required
services:
  - docker

before_install:
  - docker build -t oneandwholly/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true oneandwholly/react-test npm run test -- --coverage

after_success:
  - docker build -t oneandwholly/multi-client ./client
  - docker build -t oneandwholly/multi-nginx ./nginx
  - docker build -t oneandwholly/multi-server ./server
  - docker build -t oneandwholly/multi-worker ./worker
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push to docker hub
  - docker push oneandwholly/multi-client
  - docker push oneandwholly/multi-nginx
  - docker push oneandwholly/multi-server
  - docker push oneandwholly/multi-worker


